_extends: .github
repository:
  name: marandiz.co
  homepage: https://marandiz.co
branches:
  - name: master
    protection:
      required_status_checks:
        contexts: ['WIP', 'continuous-integration/travis-ci']
  - name: gh-pages
    protection:
      enforce_admins: true
