language: node_js
cache: npm
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - marco.marandiz@gmail.com
      - saiichihashimoto@gmail.com
    on_success: never
    on_failure: always
script:
  - npm run build && npx lint-my-app lint
jobs:
  include:
    - stage: test
      if: type = pull_request
    - stage: release
      if: type = push
      script: skip
      before_deploy: npm run build
      deploy:
        provider: pages
        fqdn: marandiz.co
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages
        local_dir: build
        skip_cleanup: true
        keep_history: true
