language: node_js
cache: npm
node_js:
  - "12"
script:
  - npm run build
jobs:
  include:
    - stage: release
      deploy:
        provider: pages
        fqdn: pinterestadexamples.com
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages
        local_dir: build
        skip_cleanup: true
        keep_history: true
