language: node_js
node_js:
  - "12"
notifications:
  email:
    recipients:
      - saiichihashimoto@gmail.com
    on_success: never
    on_failure: always
script:
  - npm run build
jobs:
  include:
    - stage: release
      deploy:
        provider: pages
        fqdn: pinterestadexamples.com
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages
        local_dir: build
        skip_cleanup: true
        keep_history: true
