language: node_js
cache: npm
node_js:
  - 11
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - npm run build
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: pages
        fqdn: pinterestadexamples.com
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages
        local_dir: build
        skip_cleanup: true
        keep_history: true
